### ISSUE TITLE
[Suggestion] Webhook Integration

### ISSUE THREAD

**Issue by XiNaru** [HoshiKurama/TicketManager#36]
Hey,
after all works now i have an little Suggestion.

It were very nice, if you can add the support for Discord Webhook Integrations, so, if someone create an Ticket, the Webhook write in an channel:
Name of the Creator
Ticket Content
Server, World and Coordinates

That were very nice

**Comment by HoshiKurama** [comment]
Hey there!

Check out [TMDiscordBot](https://github.com/HoshiKurama/TicketManagerDiscord) for this functionality. Please note that I haven’t written the documentation yet, but it is released. Documentation will come soon, but the plugin is simple enough. The config file will generate at `~plugins/TicketManager/addons/DiscordBot`.

**Comment by XiNaru** [comment]
Question: You had a waterfall plugin and normal.
Does that mean I need to add BOTH?
Waterfall in the proxy and the other one on the other servers?

**Comment by HoshiKurama** [comment]
Since you’re operating a network, you have two options depending on what you want:
1. *One Discord bot per server.* This case does not require the proxy version installed; just the backend servers.
2. *One Discord bot for the whole network.* This case requires the both the backend server version and proxy version to be installed. You must also set each backend server to relay mode in the config-common.yml file created by the plugin.

**Comment by XiNaru** [comment]
a question, the PROXY version must set to CLIENT or? and the plugin that runs on the end servers, must set to relay?

**Comment by XiNaru** [comment]
okay at me it doesnt work
https://pastebin.com/WdeGzCps

what have i do?

1. I have add waterfall version to proxy and the bukkit variant to the normal servers
2. i have set CLIENT mod on proxy?
3. I have set relay mode on normal servers
4. in all servers (inc proxy) i had add my own bot token from the app i created in the discord developer portal
5. in all servers (inc proxy) i had add the channel id, where the bot must post.


after that i restart the complete cloud but new the complete bot dont work

i think, only a webhook integration where very better

**Comment by HoshiKurama** [comment]
I was unable to replicate your issue. The plugin works as intended on my end. A few notes:
- Only client mode requires the Discord bot token and channel ID in the config. Relay mode ignores the config-client.yml.
- Relay mode doesn't start the bot in any way, so that error message is not possible on backend servers with the plugin in relay mode. Something about your setup is incorrect.
- If using the bot on a proxy, you won't receive ticket notifications from servers without at least one online player. This is a limitation with Paper / Spigot and not the plugin.

As for Webhook integration, I have no plans of doing that. I don't have the knowledge for such a thing, and I believe that TMDiscordBot adequately meets the needs of most people who want Discord integration. That being said, TicketManager has an extensive and documented API (TMDiscordBot actually uses this), so you are more than welcome to implement that support yourself or find someone who can.

**Comment by XiNaru** [comment]
okay i have try again but...

well this all my files:

1. config-client Proxy: https://pastebin.com/Dsjz23be
2. config-common Proxy (deleted bot token xd ): https://pastebin.com/A75h6vYa
3. config-relay lobby: https://pastebin.com/LxhiTs4E
4. config-common lobby: https://pastebin.com/SP0H3PAT
5. config-client lobby: https://pastebin.com/0cnAyc7E
6. latest-log: https://pastebin.com/np0ekf2g


well..maybe i have done an mistake
