### ISSUE TITLE
Feature request: Ticket Categories and/or Tags

### ISSUE THREAD

**Issue by w1nst0nDEV** [HoshiKurama/TicketManager#7]
Hello!

First off, great plugin! It's an amazing tool for my staff team to prioritize player <-> staff support and communication. You're doing a really good job!

Anyways, I was wondering if the assigning system for tickets could be a bit more organized with a togglable "tag" system. **Different ticket categories would allow different staff members/people to view them.** For example, there could be a "Developer" ticket type that only developers may view, which includes bug reports and feature requests. It would work something like this (or whatever is convenient for you to program in your free time):

1. Server owner configures different categories/tags for tickets, along with a color/symbol/tag for them in-chat. By default, if tags/categories are enabled, there would be an "unassigned" category. From there, each ticket would be assigned a category, each having the following attributive values:

- Name (this is the name of the category, one word, used in commands and references.)
- Color/Display name (this is the name given in the chat, such as "&5[DEV]" - This would display next to the ticket's name to denote its type.
- Description (this is the description of the tag when someone creates a ticket and hovers over the tag to assign it to a category)
- Private (whether or not a permission is required to view and modify tickets in this category)

2. When a user creates a ticket, the ticket is submitted under the default category automatically. Then, the user is sent the message that they can change their category by clicking a tag in chat, or by doing a command.
3. When staff receives the report, they can also change the ticket's category to something else, basically "forwarding" it to another sub-team of staff.
4. From there, specific staff can view specific tickets in a particular category and assign them to each other within that category.

Instead of having one single ticket pile and assigning particular staff members to those tickets, it might be more proficient to have the option available where assigning/viewing/commenting is restricted to a particular section of the staff team or that tickets are labeled with configurable categories/tags in order to make going through tickets more proficient and easier.

Thanks!

**Comment by HoshiKurama** [comment]
Hey there! Thank you so much for using TicketManager!

  It is of my personal opinion that adding dedicated categories section would be both redundant and add unnecessary clutter to the code and to the ticket experience. That being said, I absolutely believe there is a place for "categories" to some degree. I also believe I have come up with a solution that retains my vision for TicketManager, maintains code conciseness and complexity, and also gives you and others some of the features you desire.

My idea piggybacks off the idea that tickets can be assigned to anyone or any name. Instead of adding dedicated categories, I could implement the ability to assign a ticket to a group. The group the ticket is assigned to would register to the plugin as being assigned to everyone inside of that group. While this does remove the ability for a ticket to be assigned to both a group and a player, at the end of the day you wouldn't want a ticket assigned to someone else showing up as yours, so this does not appear to be a downgrade to me.
The second idea revolves around you mentioning tickets piling up in one place. While they would still do that, I could certainly add a new command to mitigate this. By doing something like _/ticket viewAssigned_, one could look at all tickets assigned to them. This would include tickets assigned to them directly and ticket assigned to their permission group.

I hope this might be a suitable replacement for your original suggestion as it would make my life a lot easier. I'm going to make a post later better explaining this, but for now just take my word for it. Anyways, if anything with my idea doesn't sit well, please feel free to send another message my way, and hopefully we could come up with some sort of compromise.

Thanks again so much for downloading and using my plugin!
~HoshiKurama

**Comment by w1nst0nDEV** [comment]
In my eyes, that sounds like an equally good idea! This is your project -
we’re just here for feedback and suggestions!

You’re the developer of the project: Do it whatever way you’d like, I have
full faith in you. (However, please let me know when you get that posted
though - would love to read up on the idea you have in more detail & offer
more suggestions! Haha)

Thanks!!

**Comment by HoshiKurama** [comment]
Hey there!

The TicketManagerV4 pre-release code has complete working support for group assignments! It'll work with any permission plugin supporting Vault!

Thank you so much for using TicketManager,
Hoshi
